### ISSUE TITLE
LLM model invalid

### ISSUE THREAD

**Issue by jenia** [aws-samples/build-an-agentic-llm-assistant#6]
Hello.

I can't get the software to work properly. I get this response:

```
{'statusCode': 200, 'response': 'conversation: Error raised by bedrock service: An error occurred (ValidationException) when calling the InvokeModel operation: The provided model identifier is invalid. Please try again later
```
This is the model ID I'm using `amazon.titan-text-premier-v1:0`.

 I also tried using `ChatBedrockConverse` instead of `ConversationChain`:
```
    conversation_chain = ChatBedrockConverse(model=model_id)
    response = conversation_chain.invoke(user_input)
    return response
``` 
I get the exact same error.

What confuses me is that this model ID `amazon.titan-text-premier-v1:0` is valid and listed [here](https://docs.aws.amazon.com/bedrock/latest/userguide/model-ids.html):
![image](https://github.com/user-attachments/assets/035a2835-1017-4b2d-8a63-0d9c36826060)

So I'm stuck and don't know how to use that model. Can someone please give me a hint?

**Comment by mohamed-ali** [comment]
Hi jenia, this project doesn't use amazon.titan-text-premier-v1:0 currently. If you have a general questions about using a specific model on Bedrock, you can ask it on [report.aws](https://repost.aws/account/signin?from=%2Fquestions%2Fask)
